project:
  type: website
  output-dir: _site
  resources:
    - Marco_Perez_CV.pdf

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: My Projects
      - href: cv.qmd
        text: Resume
      - href: contact.qmd
        text: Contact Me


format:
  html:
    theme: flatly
    css: styles.css
    toc: false




