---
title: "Resume"
format: html
page-layout: full
---

You can view or download my CV clicking the button below:

<a class="download-btn" href="Marco_Perez_CV.pdf" target="_blank">
  <button>Download CV (PDF)</button>
</a>


---

## Professional Summary

I’m a graduate student in Applied Business Analytics at Boston University with a background in finance, tax consulting, and business analysis. I’ve worked at companies like Deloitte and HJM International Logistics, where I used data to drive strategic insights, optimize financial processes, and improve compliance.

My skillset spans data visualization (Power BI, Tableau), Python and R for analytics, and cloud technologies like AWS. I’ve applied these tools to solve real-world business problems — from uncovering tax inefficiencies to building dashboards and automating reporting workflows.

I’m passionate about combining business context with data science to deliver measurable value, and I’m constantly learning to grow as a data-driven problem solver.